name: Build and Deploy LaTeX PDF

# Triggers on push, pull_request, or manual dispatch.
# Installs LaTeX (minimal but enough for most use-cases).
# Compiles main.tex using latexmk, which handles multiple passes.
# Moves the PDF into an output/ directory.
# Uploads and deploys that folder to GitHub Pages.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra latexmk

      - name: Compile LaTeX to PDF
        run: |
          latexmk -pdf main.tex
          mkdir output
          mv main.pdf output/

      - name: Upload artifact (PDF)
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
